server:
  port: 8081

saml2:
  ap:
    metadata:
      location: http://cs-keycloak:8080/realms/SAML-IDP-Test/protocol/saml/descriptor
    signing-cert: MIICqTCCAZECBgGJl4VrrTANBgkqhkiG9w0BAQsFADAYMRYwFAYDVQQDDA1TQU1MLUlEUC1UZXN0MB4XDTIzMDcyNzEzMjIzMFoXDTMzMDcyNzEzMjQxMFowGDEWMBQGA1UEAwwNU0FNTC1JRFAtVGVzdDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM03jyUY78iZlwI7aSrXs++qGoYADPe/nPctzH2cnYBKI0NG48Rt53jTdkN6imt6GyvoadI5Rmxe98vfCYB7WPQIP+T4dOMWGt7AjDc0Ze1VGWa+hTgeQ9rY0uyB78t7mwrRVZpxnSnLo5505G74XfQXlb+ZHtBsDPMzKUvpMlGqMY6GI7AlbXEKJrc5u8KdSpp21xORd+4vEt+RES/q5vi3sDezXTuTAjaeJZlC720Qv3lHbxpTgQgTqnAuYWD7FoCR0Xt2jssNJb2cC2oM5tKubIlhRQ0wtXpLrxcEP1Vll5YAeI4bh+DruNLSVgKwYXc193uKI41QgQD4BLNkHrMCAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAcGV0mrU81oThb3I8Vrvc4g3zCAaC0PCKK9HVNZXIbFymVePzaiiiNIwJqgR83QNS/fuRPln4e7blK4c/x2h7IBk36Et5MmkVzm/i+a7Ja1V07bsQe2ZIhXYLarKaKxcqYl8RifqyICmjzDKWPUF3e97zVzlyGAFRe8rZyZbGlJ3FDIDMB3g1JrjaRRC+HidUAwTaY6I2yNYPAiUPH7xUNc2p+8CVa5XK7HV+EJ659XmjNGpia7hOl6hMWpi/naOS1301j2XGFDXemtRPf4tFN/msHDddPNKV4XiWhtT7CGu/JGDi2eaMfdW/Any9BWkjiahw0mEJCG6APQ+a9+WF0Q==
  rp:
    signing:
      # this pair was generated with:
      # openssl req -newkey rsa:2048 -nodes -keyout rp-key.key -x509 -days 365 -out rp-certificate.crt
      cert-location: /config/rp-certificate.crt
      key-location: /config/rp-key.key
