GET http://localhost:8080/realms/master/rest-demo/hello

###

POST http://localhost:8080/realms/SAML-IDP-Test/rest-demo/link
Content-Type: application/json

{
  "userEmail" : "carsten@spraener.de",
  "clientID": "http://localhost:8081/saml2/service-provider-metadata/saml-app"
}

###
POST http://localhost:8080/realms/SAML-IDP-Test/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=admin_cli&username=test&password=12345
###
